### ISSUE TITLE
Koha Backup >>Installation>>Mail Configuration>>mrc file upload through cmd...

### ISSUE THREAD

**Issue by yashu1wwww** [PTFS-Europe/koha#135]
👉Koha Installation For Ubuntu

https://youtu.be/1kPS8Xl2PAA?feature=shared

👉Cmd To upload MRC file

https://kohageek.blogspot.com/2016/05/bulk-marc-import-using-command-line.html

👉Email configuration(At 10:15 in the video, they generate an app password, but you need to enter your Gmail password)

https://youtu.be/P705sWqC9Xs?feature=shared

After These,

👉Follow this process to generate an app password in Google: 

Go to My Account > Security > Click on 2-Factor Authentication 

Scroll down to find the option called 

"App Password." 

Click on it, provide a name,then create

 copy the 16-letter code, and paste it below where it asked.(and save it somewhere)

https://texicon.in/koha-email-configuration-set-up-smtp-servers-without-external-mta/

**Comment by mrenvoize** [comment]
Reported to the authorities as an attempted Phishing attack.
