### ISSUE TITLE
Fallback if British Library fail to come up with the material

### ISSUE THREAD

**Issue by jonathanfield** [PTFS-Europe/koha#14]
In the OPAC
cgi-bin/koha/opac-ill.pl?op=new
if the search returns 0 results allow end-user to manually enter basic request details in order to submit request and allow staff to do more research.

**Comment by janetc** [comment]
Feedback from MHRA:
The majority of requests from their users are for pre-publication materials which won't be on the British Library, so a form to allow manual entry is an essential for them.

**Comment by a-sassmannshausen** [comment]
I'm working on this.
I want this implementation to be:
- enter fields by librarian
- store as valid interlibrary loan "manual_entry"
- one-click check and if available, merge into API record (so in manage ill: click a tab link, which would compare the manually entered form against the the API backend, and if there is a result, the member of staff should be able to confirm that that is the record they are interested in, thus turning "manual_entry" into an ordinary ill)

To achieve this, the "manual entry" form should be supplied by the API backend, to be able to map the "manual_entry" populated fields with the API backend "advanced search" functionality.

Currently the "manual_entry" form is populated correctly, and I'm now working on saving the created ILL locally.  A future patch set would allow for the merge.

**Comment by a-sassmannshausen** [comment]
This is in alpha, implemented with 'ae4c0ba Implement manual entry form.'.

**Comment by a-sassmannshausen** [comment]
Implemented fully in '461757b Finalize manual entry.'
