### ISSUE TITLE
Return to Search box on OPAC

### ISSUE THREAD

**Issue by jonathanfield** [PTFS-Europe/koha#15]
From the search results page
cgi-bin/koha/opac-ill.pl?op=search&query_value=&author=marr&start_rec=11
allow the user to return back to the search box easily in order to correct/change and re-submit the search.

**Comment by a-sassmannshausen** [comment]
Implemented with commit 8585f42fdb456ff655f075442df96e04c497aad5.

Also in staff client. Active on dev env.
