### ISSUE TITLE
Add Copyright Clearance facility

### ISSUE THREAD

**Issue by jonathanfield** [PTFS-Europe/koha#16]
add the ability to be able to record that a user has accepted copyright clearance and store so that it can be reported on for CLA returns

https://docs.google.com/a/ptfs-europe.com/document/d/1kzyfguPQ3iUInNs67TOaC1xs0r4hgDDVWnzd1E4Lhko/edit?usp=sharing

**Comment by a-sassmannshausen** [comment]
Implementing a basic copyright clearance acknowledgement system in core ILLModule as a sytem preference.

Extended functionality will be covered by #108

**Comment by a-sassmannshausen** [comment]
Implemented a generic copyright clearance syspref for new patches for ILLModule.

**Comment by mrenvoize** [comment]
Blimey! That's a resurrection and a half!
