### ISSUE TITLE
Add filters on ILL management home screen

### ISSUE THREAD

**Issue by jonathanfield** [PTFS-Europe/koha#18]
Add the ability to be able to filter the list of request from 
cgi-bin/koha/ill/ill-requests.pl

A left-hand filter menu (like in acquisitions) would be good which allows you to filter the ILL requests based on various elements of the request. Suggestions would be:
Status, date_placed, dated_modified, date_completed, request_type, service_branch, needed_by, borrower cardnumber. 

In fact, the search box on the existing page could go if the filters are correct.

**Comment by a-sassmannshausen** [comment]
I think switching to the use of data tables for the results tables would largely alleviate this problem.  I'll look into that first.

**Comment by a-sassmannshausen** [comment]
I have added datatables.  It seems to provide most of the desired filters, but I think it would still be worth adding the facets.

**Comment by a-sassmannshausen** [comment]
Now implemented facets.
