### ISSUE TITLE
Display cardnumber/name instead of borrowernumber

### ISSUE THREAD

**Issue by jonathanfield** [PTFS-Europe/koha#19]
Whereever the borrowernumber displays, replace it with a cardnumber and name with a hypertext link to the borrower record, e.g. 

cgi-bin/koha/ill/ill-requests.pl
cgi-bin/koha/ill/ill-manage.pl?op=view&rq=1

**Comment by janetc** [comment]
Feedback from SLHL - confirmed as a requirement for them so they can eaisly contact borrower.

**Comment by a-sassmannshausen** [comment]
Implemented with latest patch set: 3ad9eb4.
Deployed to dev system and SLHL.
