### ISSUE TITLE
Implement Add Address service

### ISSUE THREAD

**Issue by jonathanfield** [PTFS-Europe/koha#20]
I'm guessing 90% + of requests these days are direct email to the end user from the BL (via electronic delivery, email of PDF). In which case it's important we implement the BL Add Address service. 

A checkbox on
cgi-bin/koha/ill/ill-manage.pl?rq=1&op=progress

Add Address submits the email of the borrower to the BL as part of the request so that they know where to deliver it. 

For un-mediated requests it should be an option ALWAYS allow this (as it will be the majority at Herts. for example)

**Comment by a-sassmannshausen** [comment]
Revised workflow:
- upon request placement, verify service requirements by referencing BL API (currently returning 404 on their part, so I'm mocking this part)
- if validation fails (e.g. physical delivery address is invalid, or email is invalid), signal error.
- if all ok, proceed with request, physical delivery defaulting to branch address, digital delivery, to borrower email.

**Comment by a-sassmannshausen** [comment]
Implemented with 91f2283 Implement hard delivery address validation.
For now failure to validate results in die.  This should be made friendlier.
