### ISSUE TITLE
Add BL IDs and passwords to library branches

### ISSUE THREAD

**Issue by jonathanfield** [PTFS-Europe/koha#22]
.. so that each library can facilitate it's own requests. By default, use the BL IDs from the branch which is servicing the ILL request.

**Comment by a-sassmannshausen** [comment]
Would this mean that we want to filter the ILL pages by default by ILL account (i.e. each library that has a different BL account has a separate view of the ILLs).

If so, I wonder how this might interact with Generic ILL, which might not use BL accounts at all?

**Comment by a-sassmannshausen** [comment]
This is now implemented:
- koha-conf.xml provides a section to define:
  + default ILL credentials (for fall-back or simple mode)
  + <branch> element which can be used to define per branch credentials
- The ILL logic tries to fetch credentials of the library where the user is currently logged in.
- If that fails it will use the default credentials.

**Comment by a-sassmannshausen** [comment]
(commits: 24a7190, 87dfb3b, 67eb1d7, 791d466
