### ISSUE TITLE
Store cost of item

### ISSUE THREAD

**Issue by jonathanfield** [PTFS-Europe/koha#23]
Once the request has been submitted to the BL (based on the selections made for delivery speed and format) store the cost in the database so that it can be reported on and display the cost on 
cgi-bin/koha/ill/ill-manage.pl?op=view&rq=2

**Comment by a-sassmannshausen** [comment]
This could be stored as an additional value in the borrower request attributes table.  That table is currently used as a "cache" to store "permanent" data sourced from the API — this seems a perfect candidate.

**Comment by a-sassmannshausen** [comment]
I've now implemented means for adding additional ILL module storage in the attributes table without interfering with the automatic API fetching and setting of bib data.

This should be relatively low hanging fruit now — bumping to that status.

**Comment by a-sassmannshausen** [comment]
Implemented in commit "40b4109 Store cost of ILLRequest at point of placement".
