### ISSUE TITLE
Allow Request Limits

### ISSUE THREAD

**Issue by jonathanfield** [PTFS-Europe/koha#24]
In th epatron category store the request limit by borrower type so that borrowers are limited to having only x number of active requests. We need to define what an "active" request is. Probably anything without a date_completed set. This prevents users (particularly in an un-mediated environment) from placing numerous requests and racking up unwanted costs.

**Comment by janetc** [comment]
Feedback from SLHL - slight complication with the NHS setup. They would prefer to be able to set a limit on BL requests - but, they allow unlimited Generic Requests to be placed with their Partner Libraries.  
Actually for SLHL - as they will be processing new BL requests through the staff client this is probably not a problem - they can set the number of active requests high and then staff decide whether to process as Generic ILL or BL request.

**Comment by a-sassmannshausen** [comment]
OK, I've implemented a basic framework by which:
- per branch limits can be defined in the configuration file (optionally)
- scope is implemented for per-borrower category limits
- requests that fall outside of this scope will be given the status of 'Queued' and not processed until activated at a later stage: thus borrowers can create a wishlist of ILL requests without breaking limits.

I've not yet implemented borrower category based limits.

**Comment by a-sassmannshausen** [comment]
This is implemented with my latest set of commits, both for borrower and library branch.  I decided against using borrower category table to do this.  Instead, like with the branch work, you can set up per-borrower category rules in koha-conf.
The benefit is to keep librarian visible configuration slim, and to reduce rebasing pains.
Applying these commits on top of an existing working branch will require re-visiting the koha-conf ill-configuration section.
