### ISSUE TITLE
Staff Permission to disable access to ILL

### ISSUE THREAD

**Issue by a-sassmannshausen** [PTFS-Europe/koha#25]
- Is there a staff client permission to manage ILL requests? (in version 1
there was (manageILL) Access ILL Requests )? - trivial.

**Comment by MagnusEnger** [comment]
In installer/data/mysql/atomicupdate/ill_schema.sql there is this:

    -- Userflags
    INSERT INTO userflags (bit,flag,flagdesc,defaulton)
    VALUES ('20','ill','Manage ILL requests','0');

But the value 20 is already taken by the Lists userflag, resulting in an error like this when you try to load the .sql file on current master:

    $ sudo koha-mysql kohadev < installer/data/mysql/atomicupdate/ill_schema.sql 
    ERROR 1062 (23000) at line 16: Duplicate entry '20' for key 'PRIMARY'

**Comment by a-sassmannshausen** [comment]
Fixed: staff members can now be given 2 ill privileges:
ill-manage and ill-create.

**Comment by MagnusEnger** [comment]
Nice!
