### ISSUE TITLE
After placing request on OPAC show "your request has been submitted" message

### ISSUE THREAD

**Issue by janetc** [PTFS-Europe/koha#29]
Currently on the OPAC after placing a request the page returns to your list of requests and the latest request at the bottom of the page. 
After placing a request it should show a confirmation that "your request has been submitted".
Needs an identifier so we can customise the message with jquery?

**Comment by a-sassmannshausen** [comment]
I've implemented this using bootstrap message levels. I'm also guaranteeing unique id's for each message.
