### ISSUE TITLE
Article fields need to display

### ISSUE THREAD

**Issue by janetc** [PTFS-Europe/koha#30]
Feedback from SLHL: Articles are the most commonly requested items. Displaying the article details is important for them

On both OPAC and Staff client:
After a search the following fields need to display in the list summary:
Article title
Volume
Issue/part
Page numbers.

If a request is placed the same article fields need to display in the list view and in the full request view in both OPAC and Staff clients.
If space is an issue some of the fields that are showing in the list view could be removed and just show in the full view...e.g. Publisher/Item Number/Request type ??

**Comment by a-sassmannshausen** [comment]
Thinking about it, this is already configurable using the ILL definitions yaml file.  After installation of the patch set, there will be a file in KOHA_CONF_DIR/ill/config.yaml (e.g. ~/koha-dev/etc/ill/config.yaml) that allows you to select which fields should be shown in Summary (table) view.

You can have a look at it, it should be pretty straightforward, but in essence, if you want to disappear a field, set "inSummary:" to no.  If you want it to appear, set it to "yes" (you may have to add the "inSummary:" line.

I've switched on the relevant fields on SLHL & my dev env. Have a look to see whether this solves the issue.

Alex
