### ISSUE TITLE
Generic Email notice text - define different texts per library 

### ISSUE THREAD

**Issue by janetc** [PTFS-Europe/koha#31]
Feedback from SLHL: The generic email has fixed text (which can be edited). The text needs to be able to be different for each library site. At the moment they'd have to edit it each time...

**Comment by a-sassmannshausen** [comment]
As acceptable solution: display branchcode before the name of each library in the select box.

this allows each library to distinguish from the potentially identically named partner libraries.

**Comment by a-sassmannshausen** [comment]
I've implemented the above for now. it's live on the demo server.
