### ISSUE TITLE
Request notes 

### ISSUE THREAD

**Issue by janetc** [PTFS-Europe/koha#35]
Feedback from SLHL:
This is related to tracking the progress of a Generic Email request. 
Staff need to be able to add Notes/Comments to a request.

In version one it was possible to define additional local field (ILLLocalField1, ILLLocalField2 etc).
If this is still possible in the new version then this can be considered closed!

**Comment by janetc** [comment]
Feedback from MHRA:
Users should also be able to add a note to their request from the OPAC - for example to request a preferred format.

**Comment by a-sassmannshausen** [comment]
I think we can implement this as a plugin (so it can be turned off / on).

But for now this can be implemented quite straightforwardly as an always on function using the same mechanism used for storing request cost.

**Comment by a-sassmannshausen** [comment]
Implemented fully with commits a79ee5b Add opac comments UI, 439e1a8 Add staff and opac notes to ILL Requests.
