### ISSUE TITLE
Staff client Add New ILL Request searches by borrowernumber

### ISSUE THREAD

**Issue by janetc** [PTFS-Europe/koha#36]
In the Staff client the Add New ILL request the link to the borrower is by borrowernumber. This should point to a search box for a patron search (by cardnumber/surname)

**Comment by janetc** [comment]
From SLHL feedback this will become an important one - I've upped it to Urgent.

**Comment by a-sassmannshausen** [comment]
For now, I've implemented it to accept cardnumber. Search will be the next upgrade to this issue.

**Comment by a-sassmannshausen** [comment]
Implemented surname as well as cardnumber search in "ffe34fe Surname borrower search for ill-new.".
