### ISSUE TITLE
Staff client requests need some filtering options

### ISSUE THREAD

**Issue by janetc** [PTFS-Europe/koha#37]
On the ILL Request management there are some search options to enable filtering by requests at the top of the table - e.g.Search type: Specific Request/ Requests by Borrower/ Search for:

In time there will be xxxs of requests - requests need to be grouped somehow.
Could there be grouping on this page by Status - e.g. different tabs for each request status - e.g. 1 for New Requests, 1 for Cancellation requested etc?

In the table display it needs to be possible to filter by library (the library of the patron requesting the material) - using column filters.

**Comment by a-sassmannshausen** [comment]
Fixed with commits 5e879bf and 519cabb.
Deployed.
