### ISSUE TITLE
OPAC: on search form "Type" move Article to the top

### ISSUE THREAD

**Issue by janetc** [PTFS-Europe/koha#39]
Article (for academic sites particularly) will be the most important request type. This should be moved to the top of the Type pulldown box - http://asdev.koha-ptfs.co.uk/cgi-bin/koha/opac-ill.pl.
(could do this with jquery - so no worries - I just wanted to log it!)

**Comment by a-sassmannshausen** [comment]
This list is dynamically generated, and messing with it at this stage would be a little ad-hoc.  I'll have to think about a proper mechanism to do this in future — for now, indeed, jQuery may be the best way to do this.

Alex

**Comment by janetc** [comment]
How do I remove the Urgent tag!? I added an id on opac-ill.tt and then used jquery to shift the <li> elements around as necessary.

**Comment by a-sassmannshausen** [comment]
Done. I've had a look at the id's you added, and have added them to my dev branch for the next push.
