### ISSUE TITLE
Systematize an organize ILL Statuses

### ISSUE THREAD

**Issue by a-sassmannshausen** [PTFS-Europe/koha#57]
> - Filters
> I know this wasn't on the list to test but I'm still not clear where the
> values in the Filters: Status come from. I can see:
> New request,Queued,Completed,Cancellation requested
> but not Request Reverted. I'm just trying to understand what gets written to
> the db and what doesn't for reporting purposes....suppose I ought to look in
> the db!!!

Hmm… I haven't systematized this yet.  If this isn't an issue yet on
Trello, it would be great to add this.  I don't think it's too hard, but
probably not low hanging fruit.

**Comment by janetc** [comment]
Feedback from MHRA:
There should be a way for a staff member with the right permissions to be able to put a queued request back into a state that can be processed (or cancelled)

**Comment by a-sassmannshausen** [comment]
Indeed — so they can already at the moment: just go to the ILL, click Edit, then change the "free text" field containing the "Queued" value to "New Request", and then save.

After this the user can process the ILL as normal (i.e. process, cancel, etc.).

The issue here would merely streamline the workflow by not having to edit a "free text" field, but instead being able to use a drop down box, or buttons to change the status to "New Request" or "Cancellled".

HTH.

**Comment by MagnusEnger** [comment]
It would probably make sense to pull the statuses from a list of authorized values.

**Comment by a-sassmannshausen** [comment]
This has been resolved with commits 0a71bdc, and following (see #93 for additional notes).
