### ISSUE TITLE
Moderation tab is missing

### ISSUE THREAD

**Issue by fionaborthwick1** [PTFS-Europe/koha#64]
When a request has been cancelled by a user in the opac, the status changes to be 'cancellation requested' as expected.  However the Moderation folder is not displaying in the staff interface when you choose to Manage the ILL request.

The 'moderation' folder should be present if an ILL request has the 'cancellation requested' status so that a member of library staff can approve or deny the cancellation.

**Comment by a-sassmannshausen** [comment]
Fixed in commit 'dcbd99bfff1d2a09b65b2655919a7b08fd41dc96'.
