### ISSUE TITLE
Display of results from the BL on the OPAC view - how to make more readable?

### ISSUE THREAD

**Issue by janetc** [PTFS-Europe/koha#67]
Feedback from MHRA and others:
The requests listing with results from the OPAC is very busy in the opac and the title field is too narrow. I've also been asked to widen title, hide issn/isbn, BL number etc etc....

Short-term:
JM - I can addClass using jquery for the <th> as there is an id, but the td does not seem to have an identifier that I can use.
If you could make give each of the <td> cells a class or id I will be able to use jquery to make the modifications to this view in the short term.

Longer-term:
A brief display for the column view and a clickable link to show full display might work? 

The same applies for the results from the BL AND the users own column list of requests placed.

**Comment by a-sassmannshausen** [comment]
Hello,
For the short term solution I suggest the following:
- Edit the header column using the id, as you suggest,
- Edit the column entries themselves with a selector of the form: ".span10 > table:nth-child(4) > tbody:nth-child(2) > tr > td:nth-child(2)" (this one would select the second column — the relevant bit is td:nth-child(2)).

In the long-term I'll need to add the th id to the tds of the same column too.

Thanks for pointing this out.

Alex

**Comment by a-sassmannshausen** [comment]
Chatting to Martin about Koha's XSLT theming made me think that it could be very feasible to add a further configuration layer (perhaps as yaml) that specifies what fields should be shown on what pages in the ILL module.

We would operate on 2 levels:
- spec.yaml specifies what data should be passed to the front-end, depending on "Summary / Full" view.
- display.yaml specifies what fields should be displayed on which pages (tables).

**Comment by a-sassmannshausen** [comment]
Class labels are implemented in commit 'a7faf67 Bugfix #67: Add class for opac table.'.
