### ISSUE TITLE
Fields and order of fields in Generic email text

### ISSUE THREAD

**Issue by janetc** [PTFS-Europe/koha#75]
Feedback from MHRA and SLHL:
Is there a way to specify the fields & order for the generic emails sent from the staff client – e.g. the BL specific fields are not needed to send to the other suppliers (e.g. BL identifier).
It would read better if the title was at the top of the reference.

**Comment by a-sassmannshausen** [comment]
This could be a config file thing for sure.

I don't really consider this urgent, so will add it to 1.1.  What do you think?

**Comment by janetc** [comment]
Follow up from SLHL review meeting 20-10-15: For SLHL it would be hugely beneficial if the Library branch dealing with the request could be added to the end of the generic email message.
Would this be a large piece of work?
