### ISSUE TITLE
OPAC show Date requested on a placed request

### ISSUE THREAD

**Issue by janetc** [PTFS-Europe/koha#77]
Feedback from MHRA:
On the display of a users ILL requests on the OPAC:
"The date requested  is is not visible and I think this should be present "

**Comment by a-sassmannshausen** [comment]
Will look at whether this is an easy fix, if so, I'll add it to the next patch rollout.
If not, stick it in 1.1.

**Comment by a-sassmannshausen** [comment]
Date requested is now visible in the request details view.

Implemented in new ILL version.
