### ISSUE TITLE
Staff client date filter dates are in wrong date format?

### ISSUE THREAD

**Issue by janetc** [PTFS-Europe/koha#84]
On the staff client (Herts specifically) the Date filters - e.g. Date placed/Date modified filters don't work.
However it seems to be related to the date format because if -  instead of using the dd/mm/yyyy gadget and type in a date 2015/07/22 - the filters do work.

**Comment by a-sassmannshausen** [comment]
I will need to revisit date handling in the ILL module.  At the moment it consistently uses ISO format.  Which is a good start — but now it needs to be localised for output.

**Comment by a-sassmannshausen** [comment]
Implemented in new ILL version.
