### ISSUE TITLE
Staff Client: Next page on search results fails

### ISSUE THREAD

**Issue by janetc** [PTFS-Europe/koha#87]
Add New ILL Request : do a  BL search for something that gives more than 1 page of results (e.g. biosimilars) (select borrower and branch). 
On the results page click next at the bottom to go on to the next  page of results.
Each time I am taken back to the search form with a message saying Please Note: The branch you chose is invalid.

**Comment by a-sassmannshausen** [comment]
Oha, sounds like we have a regression bug.

I'll add it to the next patch rollout, and make it urgen.

Cheers!

**Comment by a-sassmannshausen** [comment]
Fixed in 1c13c0b.
