### ISSUE TITLE
Staff client date filter enhancement

### ISSUE THREAD

**Issue by janetc** [PTFS-Europe/koha#88]
In the staff client there are the search boxes to filter by date though this seems to require an exact date.

It would be useful to be able to put in a date range or retrieve matching requests  before/after a specific date (e.g show completed requests for the current month, outstanding requests in the last 3 months etc.

**Comment by a-sassmannshausen** [comment]
Indeed, sounds like a brilliant UI improvement.

It will involve revisiting dates as a whole (which is necessary anyway), but will hence be a bit involved.

**Comment by a-sassmannshausen** [comment]
Implemented in new ILL version.
