### ISSUE TITLE
Use authorised values for ILL request statuses

### ISSUE THREAD

**Issue by MagnusEnger** [PTFS-Europe/koha#93]
Currently, ILL request statuses are implemented as a free text field:

```
status varchar(50),
```

Available statuses are defined at least in ill-requests.pl:

```
    statuses    => [ "New Request", "Queued", "Completed",
                     "Cancellation Requested"]
```

I think it would make sense to have this not as free text, but to use values from a list of authorised values.

**Comment by a-sassmannshausen** [comment]
I'm closing this issue, as your pull request and a few subsequent commits fix this.

Cheers for your work!
